import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Clock, Keyboard, MessageSquareText, MoreVertical, Pencil, Route, Settings, Trash2, Copy, X } from "lucide-react";
import { toast } from "sonner";
import sparkle from "/campaign-assets/ic-sparkle-ai.gif";
import CoMarketerButton from "./CoMarketerButton";
import JourneyStatusBadge from "./JourneyStatusBadge";
import type { JourneyDates } from "./JourneySettingsDrawer";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

/** Inline, click-to-edit journey name — same interaction as CampaignNameField
 *  (click → input, Enter/blur commits, Escape reverts), sized for this
 *  header's larger title instead of duplicating the rename logic. */
function JourneyNameField({ name, onRename }: { name: string; onRename?: (name: string) => void }) {
  const [isRenaming, setIsRenaming] = useState(false);
  const [value, setValue] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isRenaming) inputRef.current?.select();
  }, [isRenaming]);

  const start = () => {
    setValue(name);
    setIsRenaming(true);
  };
  const commit = () => {
    const next = value.trim();
    if (next && next !== name) onRename?.(next);
    setIsRenaming(false);
  };

  if (isRenaming) {
    return (
      <input
        ref={inputRef}
        autoFocus
        value={value}
        onChange={(e) => setValue(e.target.value)}
        onKeyDown={(e) => {
          if (e.key === "Enter") commit();
          else if (e.key === "Escape") setIsRenaming(false);
        }}
        onBlur={commit}
        aria-label="Journey name"
        className="w-[360px] max-w-full rounded-md border border-[#B9C4DD] bg-white px-2 py-1 font-manrope text-[20px] font-bold tracking-[0.42px] text-[#17173A] outline-none"
      />
    );
  }

  return (
    <button
      type="button"
      onClick={start}
      aria-label="Rename journey"
      className="max-w-full truncate rounded-md px-2 py-1 font-manrope text-[20px] font-bold tracking-[0.42px] text-[#17173A] transition-colors hover:bg-[#F3F6FF]"
    >
      {name}
    </button>
  );
}

/**
 * Journey Builder header / L1 actions bar (Figma node 16788:23367).
 * Row 1: journey icon + editable name + primary actions (Save, Publish
 * journey, close). Row 2: status + meta (ID, schedule once set, last edited)
 * + overflow menu / Settings / comment / history. House font Manrope stands
 * in for Figma's Nunito Sans.
 */
export default function JourneyBuilderHeader({
  name,
  created = true,
  generatedByAI = false,
  journeyId,
  dates = null,
  publishReady = true,
  onRenameJourney,
  onActivate,
  onEditObjective,
  onOpenSettings,
  onOpenShortcuts,
  onOpenCoMarketer,
}: {
  name: string;
  /**
   * Whether a journey actually exists yet. Until one is created (e.g. the AI
   * drawer is still open over an empty canvas), the header shows the name in
   * a muted "not yet created" tone with no ID / schedule meta.
   */
  created?: boolean;
  /** Shows a "Generated by AI" badge before the primary actions. */
  generatedByAI?: boolean;
  /** Shown next to the status pill once the journey exists. */
  journeyId?: string;
  /** The configured start/end schedule — unset until Settings saves one, in
   *  which case the schedule row doesn't render at all. */
  dates?: JourneyDates | null;
  /** Whether Settings has both a start/end schedule and a goal saved —
   *  "Publish journey" stays disabled (with a tooltip pointing at Settings)
   *  until both are set. Defaults to true so a caller that doesn't pass
   *  this prop keeps the button enabled, same as before this gate existed. */
  publishReady?: boolean;
  /** Called with the new name when the user commits an inline rename. */
  onRenameJourney?: (name: string) => void;
  /** Called with the journey name when "Publish journey" is tapped. */
  onActivate?: (name: string) => void;
  /**
   * Called when "Edit objective" is tapped (AI journeys only, from the
   * overflow menu) — reopens the objective drawer so the goal can be changed
   * and the journey regenerated.
   */
  onEditObjective?: () => void;
  /** Called when "Settings" is tapped, to configure the journey's schedule. */
  onOpenSettings?: () => void;
  /** Called when "Keyboard shortcuts" is tapped in the overflow menu. */
  onOpenShortcuts?: () => void;
  /** Called when "Co-marketer" is tapped — opens the docked co-marketer
   *  panel on the canvas (see JourneyBuilder's aiChatOpen). */
  onOpenCoMarketer?: () => void;
}) {
  const navigate = useNavigate();

  return (
    <header className="flex flex-col gap-2 rounded-lg bg-white px-10 py-2 shadow-[0px_5px_10px_0px_rgba(23,23,58,0.05)]">
      {/* Row 1 — title + primary actions */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <span className="grid place-items-center rounded-[5px] bg-[#F7E8FD] p-1.5">
            <Route className="h-6 w-6 text-[#BE52F2]" strokeWidth={1.9} />
          </span>
          {created ? (
            <JourneyNameField name={name} onRename={onRenameJourney} />
          ) : (
            <h1 className="font-manrope text-[20px] font-bold tracking-[0.42px] text-[#6F6F8D]">{name}</h1>
          )}
        </div>

        <div className="flex items-center gap-4">
          {generatedByAI && (
            <span className="flex items-center gap-1.5 rounded-full border border-[#C9D7F5] bg-[#E7EDFF] px-3 py-1.5 font-manrope text-xs font-semibold tracking-[0.2px] text-[#2F68E5]">
              <img src={sparkle} alt="" className="h-4 w-4" />
              Generated by AI
            </span>
          )}
          <CoMarketerButton label="Co-marketer" onClick={onOpenCoMarketer} />
          <button className="dc-btn dc-btn-secondary-blue">
            Save
          </button>
          <Tooltip>
            <TooltipTrigger asChild>
              {/* Not a native `disabled` button while unready — a disabled
                  element suppresses hover/pointer events in most browsers,
                  which would silence the very tooltip meant to explain why
                  it's unready. The disabled look/behavior is applied by
                  hand instead: matching `.dc-btn-primary:disabled` colors,
                  `aria-disabled` for a11y, and a guarded no-op click. */}
              <button
                aria-disabled={!publishReady}
                onClick={() => {
                  if (!publishReady) return;
                  onActivate
                    ? onActivate(name)
                    : navigate("/journeys", {
                        state: { activatedJourney: { name, generatedByAI } },
                      });
                }}
                className={`dc-btn dc-btn-primary ${
                  publishReady ? "" : "cursor-not-allowed border-transparent !bg-[var(--btn-primary-disabled)] shadow-none"
                }`}
              >
                Publish journey
              </button>
            </TooltipTrigger>
            <TooltipContent
              side="bottom"
              className="border-0 bg-foreground text-background text-[12px] leading-[16px] px-[8px] py-[4px]"
            >
              {publishReady ? "R" : "Set your journey's settings first"}
            </TooltipContent>
          </Tooltip>
          <button
            aria-label="Close"
            onClick={() => navigate("/journeys")}
            className="grid h-9 w-9 place-items-center rounded border-[1.5px] border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <X className="h-5 w-5" strokeWidth={1.9} />
          </button>
        </div>
      </div>

      <div className="h-px w-full bg-[#DDE2EE]" />

      {/* Row 2 — status + meta + secondary actions */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          {/* A journey built here has never been activated yet — always Draft. */}
          <JourneyStatusBadge status="DRAFT" />
          {created && (
            <div className="flex items-center gap-2 font-manrope text-sm font-semibold tracking-[0.42px] text-[#6F6F8D]">
              {journeyId && <span>ID: {journeyId}</span>}
              {dates && (
                <>
                  {journeyId && <span className="h-4 w-px bg-[#DDE2EE]" />}
                  <span>
                    Start - End date: {dates.startLabel} - {dates.endLabel}
                  </span>
                </>
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-4">
          <button type="button" onClick={onOpenSettings} className="dc-btn dc-btn-secondary">
            <Settings className="h-3.5 w-3.5" strokeWidth={1.9} />
            Settings
          </button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <button
                type="button"
                aria-label="More journey options"
                className="grid h-7 w-7 place-items-center rounded border border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF] data-[state=open]:bg-[#F3F6FF]"
              >
                <MoreVertical className="h-4 w-4" strokeWidth={1.9} />
              </button>
            </DropdownMenuTrigger>
            <DropdownMenuContent
              align="end"
              sideOffset={6}
              className="z-[60] w-[190px] rounded-lg border border-[#DDE2EE] bg-white p-1 font-manrope shadow-[0_12px_32px_rgba(23,23,58,0.14)]"
            >
              {generatedByAI && (
                <DropdownMenuItem
                  onClick={onEditObjective}
                  className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-[13px] text-[#17173A] focus:bg-[#F3F6FF]"
                >
                  <Pencil className="h-3.5 w-3.5" strokeWidth={1.9} /> Edit objective
                </DropdownMenuItem>
              )}
              <DropdownMenuItem
                onClick={() => toast.success("Journey duplicated")}
                className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-[13px] text-[#17173A] focus:bg-[#F3F6FF]"
              >
                <Copy className="h-3.5 w-3.5" strokeWidth={1.9} /> Duplicate journey
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={onOpenShortcuts}
                className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-[13px] text-[#17173A] focus:bg-[#F3F6FF]"
              >
                <Keyboard className="h-3.5 w-3.5" strokeWidth={1.9} /> Keyboard shortcuts
              </DropdownMenuItem>
              <DropdownMenuItem
                onClick={() => {
                  toast.success("Journey deleted");
                  navigate("/journeys");
                }}
                className="flex cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-[13px] text-[#D92D20] focus:bg-[#FDECEA]"
              >
                <Trash2 className="h-3.5 w-3.5" strokeWidth={1.9} /> Delete journey
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <span className="h-6 w-px bg-[#DDE2EE]" />
          <button
            aria-label="Comments"
            className="grid h-7 w-7 place-items-center rounded border border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <MessageSquareText className="h-4 w-4" strokeWidth={1.9} />
          </button>
          <button
            aria-label="History"
            className="grid h-7 w-7 place-items-center rounded border border-[#DDE2EE] bg-white text-[#6F6F8D] transition-colors hover:bg-[#F3F6FF]"
          >
            <Clock className="h-4 w-4" strokeWidth={1.9} />
          </button>
        </div>
      </div>
    </header>
  );
}
